[2024-04-01T12:06:21.111+0000] {processor.py:161} INFO - Started process (PID=22334) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:06:21.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:06:21.115+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:06:21.114+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:06:21.158+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:06:21.150+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:06:21.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:06:21.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.073 seconds
[2024-04-01T12:06:51.864+0000] {processor.py:161} INFO - Started process (PID=22389) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:06:51.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:06:51.870+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:06:51.869+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:06:51.896+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:06:51.894+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:06:51.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:06:51.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.053 seconds
[2024-04-01T12:07:22.047+0000] {processor.py:161} INFO - Started process (PID=22445) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:07:22.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:07:22.050+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:07:22.050+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:07:22.073+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:07:22.070+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:07:22.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:07:22.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T12:07:52.171+0000] {processor.py:161} INFO - Started process (PID=22500) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:07:52.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:07:52.175+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:07:52.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:07:52.193+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:07:52.191+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:07:52.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:07:52.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.047 seconds
[2024-04-01T12:08:22.410+0000] {processor.py:161} INFO - Started process (PID=22555) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:08:22.412+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:08:22.414+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:08:22.414+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:08:22.446+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:08:22.440+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:08:22.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:08:22.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.071 seconds
[2024-04-01T12:08:53.377+0000] {processor.py:161} INFO - Started process (PID=22610) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:08:53.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:08:53.380+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:08:53.380+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:08:53.406+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:08:53.403+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:08:53.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:08:53.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.051 seconds
[2024-04-01T12:09:24.197+0000] {processor.py:161} INFO - Started process (PID=22665) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:09:24.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:09:24.202+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:09:24.201+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:09:24.226+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:09:24.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:09:24.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:09:24.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.058 seconds
[2024-04-01T12:09:55.001+0000] {processor.py:161} INFO - Started process (PID=22720) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:09:55.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:09:55.005+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:09:55.005+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:09:55.030+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:09:55.027+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:09:55.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:09:55.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.049 seconds
[2024-04-01T12:10:25.894+0000] {processor.py:161} INFO - Started process (PID=22775) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:10:25.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:10:25.898+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:10:25.898+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:10:25.922+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:10:25.917+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:10:25.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:10:25.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.050 seconds
[2024-04-01T12:10:56.071+0000] {processor.py:161} INFO - Started process (PID=22830) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:10:56.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:10:56.074+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:10:56.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:10:56.096+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:10:56.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:10:56.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:10:56.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T12:11:27.040+0000] {processor.py:161} INFO - Started process (PID=22885) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:11:27.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:11:27.043+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:11:27.043+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:11:27.059+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:11:27.057+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:11:27.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:11:27.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.047 seconds
[2024-04-01T12:11:57.877+0000] {processor.py:161} INFO - Started process (PID=22940) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:11:57.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:11:57.882+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:11:57.881+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:11:57.901+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:11:57.897+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:11:57.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:11:57.930+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.057 seconds
[2024-04-01T12:12:28.484+0000] {processor.py:161} INFO - Started process (PID=22995) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:12:28.485+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:12:28.488+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:12:28.488+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:12:28.511+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:12:28.508+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:12:28.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:12:28.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.056 seconds
[2024-04-01T12:12:59.154+0000] {processor.py:161} INFO - Started process (PID=23050) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:12:59.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:12:59.159+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:12:59.158+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:12:59.187+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:12:59.183+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:12:59.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:12:59.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.054 seconds
[2024-04-01T12:15:10.975+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:15:10.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:15:10.979+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:15:10.978+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:15:10.990+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:15:10.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:15:10.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:15:11.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.037 seconds
[2024-04-01T12:15:41.536+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:15:41.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:15:41.540+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:15:41.539+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:15:41.564+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:15:41.561+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:15:41.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:15:41.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.051 seconds
[2024-04-01T12:16:12.358+0000] {processor.py:161} INFO - Started process (PID=153) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:16:12.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:16:12.362+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:16:12.361+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:16:12.380+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:16:12.377+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:16:12.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:16:12.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.043 seconds
[2024-04-01T12:16:42.574+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:16:42.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:16:42.577+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:16:42.577+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:16:42.604+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:16:42.598+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:16:42.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:16:42.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.053 seconds
[2024-04-01T12:17:12.741+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:17:12.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:17:12.745+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:17:12.745+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:17:12.767+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:17:12.764+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:17:12.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:17:12.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.048 seconds
[2024-04-01T12:17:42.849+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:17:42.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:17:42.852+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:17:42.851+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:17:42.872+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:17:42.869+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:17:42.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:17:42.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.042 seconds
[2024-04-01T12:18:13.080+0000] {processor.py:161} INFO - Started process (PID=373) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:18:13.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:18:13.084+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:18:13.083+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:18:13.100+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:18:13.097+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:18:13.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:18:13.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.043 seconds
[2024-04-01T12:18:43.746+0000] {processor.py:161} INFO - Started process (PID=428) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:18:43.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:18:43.751+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:18:43.750+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:18:43.769+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:18:43.766+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:18:43.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:18:43.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T12:19:14.247+0000] {processor.py:161} INFO - Started process (PID=483) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:19:14.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:19:14.251+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:19:14.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:19:14.272+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:19:14.269+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:19:14.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:19:14.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.045 seconds
[2024-04-01T12:19:44.768+0000] {processor.py:161} INFO - Started process (PID=538) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:19:44.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:19:44.773+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:19:44.772+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:19:44.795+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:19:44.790+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:19:44.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:19:44.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.049 seconds
[2024-04-01T12:20:15.399+0000] {processor.py:161} INFO - Started process (PID=593) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:20:15.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:20:15.404+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:20:15.403+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:20:15.425+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:20:15.419+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:20:15.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:20:15.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.074 seconds
[2024-04-01T12:20:46.100+0000] {processor.py:161} INFO - Started process (PID=648) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:20:46.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:20:46.104+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:20:46.104+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:20:46.121+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:20:46.118+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:20:46.123+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:20:46.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.043 seconds
[2024-04-01T12:21:16.568+0000] {processor.py:161} INFO - Started process (PID=703) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:21:16.569+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:21:16.572+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:21:16.571+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:21:16.598+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:21:16.593+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:21:16.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:21:16.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.052 seconds
[2024-04-01T12:21:47.144+0000] {processor.py:161} INFO - Started process (PID=757) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:21:47.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:21:47.148+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:21:47.148+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:21:47.166+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:21:47.163+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:21:47.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:21:47.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.050 seconds
[2024-04-01T12:22:17.901+0000] {processor.py:161} INFO - Started process (PID=812) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:22:17.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:22:17.905+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:22:17.905+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:22:17.930+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:22:17.924+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:22:17.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:22:17.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.053 seconds
[2024-04-01T12:22:48.835+0000] {processor.py:161} INFO - Started process (PID=868) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:22:48.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:22:48.839+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:22:48.838+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:22:48.857+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:22:48.853+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:22:48.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:22:48.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.045 seconds
[2024-04-01T12:23:19.313+0000] {processor.py:161} INFO - Started process (PID=923) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:23:19.314+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:23:19.317+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:23:19.317+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:23:19.335+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:23:19.331+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:23:19.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:23:19.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.051 seconds
[2024-04-01T12:23:49.826+0000] {processor.py:161} INFO - Started process (PID=978) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:23:49.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:23:49.830+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:23:49.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:23:49.848+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:23:49.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:23:49.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:23:49.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.041 seconds
[2024-04-01T12:24:20.322+0000] {processor.py:161} INFO - Started process (PID=1033) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:24:20.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:24:20.326+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:24:20.326+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:24:20.349+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:24:20.345+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:24:20.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:24:20.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.049 seconds
[2024-04-01T12:24:50.949+0000] {processor.py:161} INFO - Started process (PID=1088) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:24:50.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:24:50.952+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:24:50.952+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:24:50.977+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:24:50.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:24:50.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:24:51.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.057 seconds
[2024-04-01T12:25:21.429+0000] {processor.py:161} INFO - Started process (PID=1143) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:25:21.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:25:21.432+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:25:21.432+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:25:21.451+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:25:21.447+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:25:21.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:25:21.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T12:25:51.871+0000] {processor.py:161} INFO - Started process (PID=1198) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:25:51.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:25:51.874+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:25:51.874+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:25:51.893+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:25:51.889+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:25:51.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:25:51.913+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.046 seconds
[2024-04-01T12:26:22.762+0000] {processor.py:161} INFO - Started process (PID=1253) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:26:22.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:26:22.766+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:26:22.766+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:26:22.790+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:26:22.787+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:26:22.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:26:22.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.052 seconds
[2024-04-01T12:26:53.260+0000] {processor.py:161} INFO - Started process (PID=1308) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:26:53.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:26:53.265+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:26:53.264+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:26:53.289+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:26:53.284+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:26:53.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:26:53.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.048 seconds
[2024-04-01T12:27:23.732+0000] {processor.py:161} INFO - Started process (PID=1363) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:27:23.734+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:27:23.737+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:27:23.737+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:27:23.763+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:27:23.757+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:27:23.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:27:23.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.055 seconds
[2024-04-01T12:27:54.255+0000] {processor.py:161} INFO - Started process (PID=1418) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:27:54.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:27:54.259+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:27:54.259+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:27:54.277+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:27:54.274+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:27:54.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:27:54.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.045 seconds
[2024-04-01T12:28:24.791+0000] {processor.py:161} INFO - Started process (PID=1473) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:28:24.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:28:24.794+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:28:24.794+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:28:24.808+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:28:24.805+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:28:24.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:28:24.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.037 seconds
[2024-04-01T12:28:55.359+0000] {processor.py:161} INFO - Started process (PID=1528) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:28:55.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:28:55.362+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:28:55.362+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:28:55.376+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:28:55.374+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:28:55.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:28:55.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.036 seconds
[2024-04-01T12:29:25.779+0000] {processor.py:161} INFO - Started process (PID=1583) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:29:25.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:29:25.783+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:29:25.782+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:29:25.805+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:29:25.801+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:29:25.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:29:25.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.057 seconds
[2024-04-01T12:29:56.276+0000] {processor.py:161} INFO - Started process (PID=1638) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:29:56.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:29:56.280+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:29:56.280+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:29:56.298+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:29:56.294+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:29:56.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:29:56.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.045 seconds
[2024-04-01T12:30:26.644+0000] {processor.py:161} INFO - Started process (PID=1693) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:30:26.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:30:26.648+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:30:26.647+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:30:26.671+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:30:26.666+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:30:26.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:30:26.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.048 seconds
[2024-04-01T12:30:57.331+0000] {processor.py:161} INFO - Started process (PID=1748) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:30:57.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:30:57.334+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:30:57.334+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:30:57.350+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:30:57.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:30:57.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:30:57.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.048 seconds
[2024-04-01T12:31:28.028+0000] {processor.py:161} INFO - Started process (PID=1803) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:31:28.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:31:28.031+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:31:28.031+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:31:28.054+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:31:28.050+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:31:28.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:31:28.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.052 seconds
[2024-04-01T12:31:58.607+0000] {processor.py:161} INFO - Started process (PID=1858) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:31:58.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:31:58.611+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:31:58.611+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:31:58.629+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:31:58.625+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:31:58.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:31:58.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.041 seconds
[2024-04-01T12:32:29.218+0000] {processor.py:161} INFO - Started process (PID=1913) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:32:29.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:32:29.222+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:32:29.222+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:32:29.247+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:32:29.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:32:29.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:32:29.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.053 seconds
[2024-04-01T12:32:59.699+0000] {processor.py:161} INFO - Started process (PID=1974) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:32:59.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:32:59.702+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:32:59.702+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:32:59.719+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:32:59.716+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:32:59.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:32:59.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.043 seconds
[2024-04-01T12:33:30.734+0000] {processor.py:161} INFO - Started process (PID=2029) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:33:30.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:33:30.737+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:33:30.737+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:33:30.760+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:33:30.756+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:33:30.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:33:30.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.050 seconds
[2024-04-01T12:34:01.112+0000] {processor.py:161} INFO - Started process (PID=2084) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:34:01.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:34:01.116+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:34:01.115+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:34:01.137+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:34:01.133+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:34:01.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:34:01.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.053 seconds
[2024-04-01T12:34:31.984+0000] {processor.py:161} INFO - Started process (PID=2139) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:34:31.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:34:31.988+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:34:31.987+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:34:32.012+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:34:32.007+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:34:32.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:34:32.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.061 seconds
[2024-04-01T12:35:02.593+0000] {processor.py:161} INFO - Started process (PID=2194) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:35:02.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:35:02.596+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:35:02.596+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:35:02.615+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:35:02.611+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:35:02.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:35:02.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.050 seconds
[2024-04-01T12:35:33.418+0000] {processor.py:161} INFO - Started process (PID=2249) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:35:33.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:35:33.422+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:35:33.422+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:35:33.455+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:35:33.448+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:35:33.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:35:33.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.066 seconds
[2024-04-01T12:36:04.428+0000] {processor.py:161} INFO - Started process (PID=2304) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:36:04.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:36:04.431+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:36:04.431+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:36:04.450+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:36:04.447+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:36:04.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:36:04.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.042 seconds
[2024-04-01T12:36:35.460+0000] {processor.py:161} INFO - Started process (PID=2359) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:36:35.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:36:35.464+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:36:35.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:36:35.485+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:36:35.482+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:36:35.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:36:35.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.054 seconds
[2024-04-01T12:37:06.392+0000] {processor.py:161} INFO - Started process (PID=2414) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:37:06.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:37:06.396+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:37:06.396+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:37:06.419+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:37:06.414+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:37:06.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:37:06.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.052 seconds
[2024-04-01T12:37:37.035+0000] {processor.py:161} INFO - Started process (PID=2469) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:37:37.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:37:37.039+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:37:37.039+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:37:37.063+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:37:37.060+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:37:37.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:37:37.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.050 seconds
[2024-04-01T12:38:07.699+0000] {processor.py:161} INFO - Started process (PID=2525) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:38:07.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:38:07.703+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:38:07.703+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:38:07.726+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:38:07.721+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:38:07.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:38:07.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.048 seconds
[2024-04-01T12:38:38.338+0000] {processor.py:161} INFO - Started process (PID=2580) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:38:38.339+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:38:38.341+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:38:38.341+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:38:38.356+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:38:38.353+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:38:38.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:38:38.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.039 seconds
[2024-04-01T12:39:09.141+0000] {processor.py:161} INFO - Started process (PID=2635) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:39:09.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:39:09.145+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:39:09.144+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:39:09.163+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:39:09.160+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:39:09.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:39:09.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.050 seconds
[2024-04-01T12:39:39.847+0000] {processor.py:161} INFO - Started process (PID=2690) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:39:39.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:39:39.850+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:39:39.850+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:39:39.869+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:39:39.865+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:39:39.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:39:39.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.043 seconds
[2024-04-01T12:40:10.448+0000] {processor.py:161} INFO - Started process (PID=2745) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:40:10.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:40:10.451+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:40:10.451+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:40:10.477+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:40:10.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:40:10.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:40:10.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.061 seconds
[2024-04-01T12:40:41.323+0000] {processor.py:161} INFO - Started process (PID=2800) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:40:41.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:40:41.327+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:40:41.326+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:40:41.343+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:40:41.340+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:40:41.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:40:41.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.053 seconds
[2024-04-01T12:41:12.149+0000] {processor.py:161} INFO - Started process (PID=2855) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:41:12.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:41:12.152+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:41:12.151+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:41:12.171+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:41:12.167+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:41:12.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:41:12.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.051 seconds
[2024-04-01T12:41:42.630+0000] {processor.py:161} INFO - Started process (PID=2910) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:41:42.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:41:42.633+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:41:42.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:41:42.655+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:41:42.651+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:41:42.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:41:42.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.048 seconds
[2024-04-01T12:42:13.207+0000] {processor.py:161} INFO - Started process (PID=2965) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:42:13.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:42:13.211+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:42:13.211+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:42:13.235+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:42:13.230+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:42:13.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:42:13.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.052 seconds
[2024-04-01T12:42:43.778+0000] {processor.py:161} INFO - Started process (PID=3020) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:42:43.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:42:43.782+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:42:43.782+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:42:43.801+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:42:43.797+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:42:43.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:42:43.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T12:43:14.369+0000] {processor.py:161} INFO - Started process (PID=3075) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:43:14.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:43:14.372+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:43:14.372+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:43:14.390+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:43:14.386+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:43:14.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:43:14.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.047 seconds
[2024-04-01T12:43:44.903+0000] {processor.py:161} INFO - Started process (PID=3130) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:43:44.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:43:44.908+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:43:44.907+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:43:44.925+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:43:44.922+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:43:44.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:43:44.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.047 seconds
[2024-04-01T12:44:15.454+0000] {processor.py:161} INFO - Started process (PID=3185) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:44:15.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:44:15.458+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:44:15.457+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:44:15.479+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:44:15.475+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:44:15.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:44:15.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.048 seconds
[2024-04-01T12:44:46.140+0000] {processor.py:161} INFO - Started process (PID=3240) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:44:46.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:44:46.143+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:44:46.143+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:44:46.159+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:44:46.155+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:44:46.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:44:46.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.038 seconds
[2024-04-01T12:45:16.955+0000] {processor.py:161} INFO - Started process (PID=3295) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:45:16.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:45:16.958+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:45:16.958+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:45:16.973+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:45:16.971+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:45:16.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:45:16.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.042 seconds
[2024-04-01T12:45:47.608+0000] {processor.py:161} INFO - Started process (PID=3350) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:45:47.609+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:45:47.611+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:45:47.611+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:45:47.629+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:45:47.626+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:45:47.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:45:47.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.049 seconds
[2024-04-01T12:46:18.262+0000] {processor.py:161} INFO - Started process (PID=3405) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:46:18.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:46:18.265+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:46:18.265+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:46:18.284+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:46:18.281+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:46:18.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:46:18.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T12:46:48.959+0000] {processor.py:161} INFO - Started process (PID=3460) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:46:48.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:46:48.963+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:46:48.963+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:46:48.976+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:46:48.974+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:46:48.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:46:48.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.037 seconds
[2024-04-01T12:47:19.596+0000] {processor.py:161} INFO - Started process (PID=3515) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:47:19.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:47:19.600+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:47:19.599+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:47:19.618+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:47:19.615+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:47:19.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:47:19.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.050 seconds
[2024-04-01T12:47:50.180+0000] {processor.py:161} INFO - Started process (PID=3570) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:47:50.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:47:50.183+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:47:50.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:47:50.201+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:47:50.198+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:47:50.203+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:47:50.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T12:48:20.845+0000] {processor.py:161} INFO - Started process (PID=3625) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:48:20.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:48:20.849+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:48:20.849+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:48:20.869+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:48:20.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:48:20.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:48:20.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.052 seconds
[2024-04-01T12:48:51.583+0000] {processor.py:161} INFO - Started process (PID=3680) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:48:51.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:48:51.589+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:48:51.588+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:48:51.615+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:48:51.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:48:51.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:48:51.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.066 seconds
[2024-04-01T12:49:22.310+0000] {processor.py:161} INFO - Started process (PID=3735) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:49:22.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:49:22.313+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:49:22.313+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:49:22.328+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:49:22.325+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:49:22.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:49:22.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.042 seconds
[2024-04-01T12:49:53.013+0000] {processor.py:161} INFO - Started process (PID=3790) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:49:53.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:49:53.017+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:49:53.017+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:49:53.034+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:49:53.031+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:49:53.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:49:53.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T12:50:23.781+0000] {processor.py:161} INFO - Started process (PID=3845) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:50:23.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:50:23.785+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:50:23.784+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:50:23.807+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:50:23.803+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:50:23.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:50:23.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.049 seconds
[2024-04-01T12:50:54.502+0000] {processor.py:161} INFO - Started process (PID=3900) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:50:54.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:50:54.505+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:50:54.505+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:50:54.519+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:50:54.516+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:50:54.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:50:54.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.048 seconds
[2024-04-01T12:51:25.095+0000] {processor.py:161} INFO - Started process (PID=3955) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:51:25.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:51:25.098+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:51:25.098+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:51:25.117+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:51:25.114+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:51:25.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:51:25.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.042 seconds
[2024-04-01T12:51:55.636+0000] {processor.py:161} INFO - Started process (PID=4010) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:51:55.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:51:55.639+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:51:55.639+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:51:55.654+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:51:55.651+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:51:55.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:51:55.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.043 seconds
[2024-04-01T12:52:26.210+0000] {processor.py:161} INFO - Started process (PID=4065) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:52:26.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:52:26.214+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:52:26.214+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:52:26.233+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:52:26.229+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:52:26.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:52:26.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.051 seconds
[2024-04-01T12:52:56.980+0000] {processor.py:161} INFO - Started process (PID=4120) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:52:56.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:52:56.984+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:52:56.983+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:52:57.003+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:52:56.999+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:52:57.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:52:57.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.043 seconds
[2024-04-01T12:53:27.711+0000] {processor.py:161} INFO - Started process (PID=4175) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:53:27.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:53:27.715+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:53:27.714+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:53:27.739+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:53:27.735+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:53:27.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:53:27.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.056 seconds
[2024-04-01T12:53:58.370+0000] {processor.py:161} INFO - Started process (PID=4230) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:53:58.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:53:58.373+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:53:58.373+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:53:58.391+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:53:58.388+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:53:58.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:53:58.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.051 seconds
[2024-04-01T12:54:29.002+0000] {processor.py:161} INFO - Started process (PID=4285) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:54:29.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:54:29.006+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:54:29.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:54:29.026+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:54:29.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:54:29.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:54:29.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.047 seconds
[2024-04-01T12:54:59.730+0000] {processor.py:161} INFO - Started process (PID=4340) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:54:59.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:54:59.733+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:54:59.733+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:54:59.751+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:54:59.748+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:54:59.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:54:59.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.047 seconds
[2024-04-01T12:55:30.464+0000] {processor.py:161} INFO - Started process (PID=4395) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:55:30.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:55:30.468+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:55:30.467+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:55:30.491+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:55:30.486+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:55:30.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:55:30.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.081 seconds
[2024-04-01T12:56:01.169+0000] {processor.py:161} INFO - Started process (PID=4456) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:56:01.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:56:01.174+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:56:01.173+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:56:01.197+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:56:01.193+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:56:01.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:56:01.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.062 seconds
[2024-04-01T12:56:32.076+0000] {processor.py:161} INFO - Started process (PID=4511) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:56:32.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:56:32.079+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:56:32.079+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:56:32.097+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:56:32.093+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:56:32.098+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:56:32.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T12:57:02.883+0000] {processor.py:161} INFO - Started process (PID=4566) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:57:02.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:57:02.886+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:57:02.885+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:57:02.899+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:57:02.897+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:57:02.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:57:02.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.036 seconds
[2024-04-01T12:57:33.581+0000] {processor.py:161} INFO - Started process (PID=4621) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:57:33.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:57:33.585+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:57:33.584+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:57:33.603+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:57:33.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:57:33.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:57:33.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.043 seconds
[2024-04-01T12:58:04.506+0000] {processor.py:161} INFO - Started process (PID=4676) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:58:04.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:58:04.510+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:58:04.509+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:58:04.530+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:58:04.526+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:58:04.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:58:04.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.057 seconds
[2024-04-01T12:58:35.289+0000] {processor.py:161} INFO - Started process (PID=4731) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:58:35.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:58:35.293+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:58:35.293+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:58:35.313+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:58:35.309+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:58:35.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:58:35.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.043 seconds
[2024-04-01T12:59:06.111+0000] {processor.py:161} INFO - Started process (PID=4786) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:59:06.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:59:06.114+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:59:06.114+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:59:06.130+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:59:06.127+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:59:06.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:59:06.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.041 seconds
[2024-04-01T12:59:36.657+0000] {processor.py:161} INFO - Started process (PID=4840) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:59:36.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T12:59:36.661+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:59:36.660+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:59:36.681+0000] {logging_mixin.py:188} INFO - [2024-04-01T12:59:36.676+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T12:59:36.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T12:59:36.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.044 seconds
[2024-04-01T13:00:07.366+0000] {processor.py:161} INFO - Started process (PID=4896) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:00:07.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T13:00:07.371+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:00:07.370+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:00:07.389+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:00:07.386+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T13:00:07.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:00:07.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.052 seconds
[2024-04-01T13:00:38.294+0000] {processor.py:161} INFO - Started process (PID=4951) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:00:38.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T13:00:38.298+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:00:38.298+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:00:38.323+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:00:38.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T13:00:38.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:00:38.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.054 seconds
[2024-04-01T13:01:09.146+0000] {processor.py:161} INFO - Started process (PID=5006) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:01:09.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T13:01:09.149+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:01:09.148+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:01:09.166+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:01:09.163+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T13:01:09.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:01:09.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.042 seconds
[2024-04-01T13:01:39.882+0000] {processor.py:161} INFO - Started process (PID=5061) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:01:39.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T13:01:39.885+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:01:39.885+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:01:39.904+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:01:39.902+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T13:01:39.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:01:39.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.050 seconds
[2024-04-01T13:02:10.634+0000] {processor.py:161} INFO - Started process (PID=5115) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:10.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T13:02:10.638+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:02:10.637+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:10.660+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:02:10.655+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T13:02:10.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:10.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.049 seconds
[2024-04-01T13:02:17.888+0000] {processor.py:161} INFO - Started process (PID=5161) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:17.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T13:02:17.891+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:02:17.891+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:17.926+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:02:17.922+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T13:02:17.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:17.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.063 seconds
[2024-04-01T13:02:27.115+0000] {processor.py:161} INFO - Started process (PID=5165) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:27.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T13:02:27.119+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:02:27.118+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:27.163+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:02:27.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T13:02:27.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:27.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.070 seconds
[2024-04-01T13:02:57.843+0000] {processor.py:161} INFO - Started process (PID=5219) to work on /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:57.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_data_pipeline.py for tasks to queue
[2024-04-01T13:02:57.846+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:02:57.846+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:57.864+0000] {logging_mixin.py:188} INFO - [2024-04-01T13:02:57.861+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/my_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_data_pipeline.py", line 8, in <module>
    from plugins.data_manipulation import main
ModuleNotFoundError: No module named 'plugins'
[2024-04-01T13:02:57.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_data_pipeline.py
[2024-04-01T13:02:57.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_data_pipeline.py took 0.047 seconds
